### ISSUE TITLE
Add convenient Optional.orElse() like getter to JsonNullable

### ISSUE THREAD

**Issue by hatzlj** [OpenAPITools/jackson-databind-nullable#1]
First of all thanks for including the nullable support in OpenAPITools. 
I would like to suggest a minor improvement to the API of JsonNullable.

Currently we would need to use something like 
```java
jsonNullableString.isPresent() ? jsonNullableString.get() : null
```
to allow inline usage of the value.

Having someting like java Optional's .orElse() would make inline usage of JsonNullable easier. 
```java
public T orElse(T other) {
  return this.isPresent ? this.value : other;
}        
```

What do you think? If you like this idea, I would be happy to submit a PR to this project.

thanks,
Jakob

**Comment by cbornet** [comment]
Yes, seems like a good idea. Your PR is welcome :smiley:
