### ISSUE TITLE
RFE: Make JsonNullable serialize properly to XML

### ISSUE THREAD

**Issue by bkabrda** [OpenAPITools/jackson-databind-nullable#10]
As discussed in https://github.com/OpenAPITools/openapi-generator/pull/3474 it would be awesome if JsonNullable would serialize correctly to XML as well. IIUC most of the heavy machinery is already present in this package and it'd only be necessary to implement the custom XML serializer which would look much like the custom JSON serializer.

**Comment by cbornet** [comment]
Of course ! Would you do a PR ? It should be close to how it's done for Optional

**Comment by bkabrda** [comment]
Yeah, I'll try to give it a shot and reach out if I can't make something work.

**Comment by bkabrda** [comment]
Heh, I was actually doing it wrong, JsonNullable works fine even with XML when properly registered on the `XmlMapper`. Do you want me to make a note in the README.md about this?

**Comment by cbornet** [comment]
Good news ! Yes we could have a note on how to register the module in the readme for both ObjectMapper and XmlMapper.

**Comment by cbornet** [comment]
Closed by #11
