### ISSUE TITLE
Add Jackson ServiceLoader support

### ISSUE THREAD

**Issue by PascalSchumacher** [OpenAPITools/jackson-databind-nullable#19]
It would be great if you could add support for the ServiceLoader of Jackson, to make it easier to register the module with Jackson (e.g. allowing `ObjectMapper#findAndRegisterModules` to find this module).

It should suffice to add a file named `com.fasterxml.jackson.databind.Module` with the content `org.openapitools.jackson.nullable.JsonNullableModule` to the `META-INF/servcies` folder of the jar.

By the way: Thank you for providing `jackson-databind-nullable`! 👍

**Comment by cbornet** [comment]
@PascalSchumacher would you do a PR for this ?

**Comment by cbornet** [comment]
Thanks for the PR ! Very nice enhancement !
