### ISSUE TITLE
Vulnerability jackson-base

### ISSUE THREAD

**Issue by wlademir** [OpenAPITools/jackson-databind-nullable#21]
upgrade parent jackson-base to latest version available central maven 2.12.2.

https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-base/2.12.2

**Comment by cbornet** [comment]
Would you do a PR for this ?

**Comment by zteater** [comment]
> Would you do a PR for this ?

Went ahead and raised a PR for this, getting flagged for High vulnerability on internal systems.

**Comment by cbornet** [comment]
Thanks @zteater  !

**Comment by zteater** [comment]
Thank you for merging this in @cbornet . Can you publish the latest to maven central?

**Comment by wlademir** [comment]
@zteater thanks for doing PR, I just saw the request now. @cbornet the version is expected to be published?
