### ISSUE TITLE
v0.2.2 not in public maven repositories

### ISSUE THREAD

**Issue by lfischer** [OpenAPITools/jackson-databind-nullable#25]
The last publicly accessible version is v0.2.1.
https://mvnrepository.com/artifact/org.openapitools/jackson-databind-nullable

**Comment by wing328** [comment]
I'll give it another try this weekend to get it published.

**Comment by horvathandris** [comment]
any luck with publishing? still only v0.2.1 available. thanks

**Comment by rvowles** [comment]
Add this to your pom so it auto-stages through Sonatype's nexus:

<plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.7</version>
            <executions>
              <execution>
                <id>deploy</id>
                <goals>
                  <goal>deploy</goal>
                </goals>
                <phase>deploy</phase>
              </execution>
            </executions>
            <configuration>
              <serverId>sonatype-staging</serverId>
              <nexusUrl>https://oss.sonatype.org/</nexusUrl>
              <autoReleaseAfterClose>true</autoReleaseAfterClose>
            </configuration>
          </plugin>

**Comment by ta7tou7** [comment]
any updates ?

**Comment by maciejtoporowicz** [comment]
Bump - any updates?

**Comment by wing328** [comment]
Released. Sorry for the delay: https://repo1.maven.org/maven2/org/openapitools/jackson-databind-nullable/0.2.2/jackson-databind-nullable-0.2.2.jar
