### ISSUE TITLE
Usage with java 9+ modules

### ISSUE THREAD

**Issue by bratkartoffel** [OpenAPITools/jackson-databind-nullable#40]
Hi,

can you please add "Automatic-Module-Name: org.openapitools.jackson.nullable" to the jar manifest?
Currently I cannot use this library in a module project.

More information about that option can be found here: https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers

Thanks,
Simon

**Comment by cbornet** [comment]
@bratkartoffel could you do a PR ?
