### ISSUE TITLE
Craft new release

### ISSUE THREAD

**Issue by bratkartoffel** [OpenAPITools/jackson-databind-nullable#44]
Thanks for applying my changes, can you please create a new release within the next days?

**Comment by kevinbioj** [comment]
This would be appreciated as the current version requires some adjustments to work with Spring Boot 3+.

**Comment by MetroMarv** [comment]
I'd also support that request!

**Comment by wing328** [comment]
Will try to do a release over the weekend.

**Comment by berndklb** [comment]
I'd also support that request! Otherwise we have to test the workaround mentioned here: https://github.com/OpenAPITools/jackson-databind-nullable/issues/39

**Comment by bszeliga** [comment]
Status for a new release?

**Comment by wing328** [comment]
tried but got 403 forbidden. will give it another try over the weekend.

**Comment by wing328** [comment]
should be done:
```
[INFO]  * Upload of locally staged artifacts finished.
[INFO]  * Closing staging repository with ID "orgopenapitools-1292".

Waiting for operation to complete...
...........................................

[INFO] Remote staged 1 repositories, finished with success.
[INFO] Remote staging repositories are being released...

Waiting for operation to complete...
...............

[INFO] Remote staging repositories released.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:20 min
[INFO] Finished at: 2023-02-13T18:03:25+08:00
[INFO] ------------------------------------------------------------------------
```

it may take some time for v0.2.5 to be visible in https://search.maven.org/artifact/org.openapitools/jackson-databind-nullable

**Comment by wing328** [comment]
available in https://search.maven.org/artifact/org.openapitools/jackson-databind-nullable
