### ISSUE TITLE
Support for javax.validation is not released

### ISSUE THREAD

**Issue by SirWayne** [OpenAPITools/jackson-databind-nullable#9]
Hi,

Can someone trigger a release for a new version? In the current version no javax.validation support is included.

Cheers
Dennis

**Comment by SirWayne** [comment]
@hatzlj @wing328 @cbornet can someone create a release?

**Comment by wing328** [comment]
We plan to release 4.0.3 today. Stay tuned.

**Comment by wing328** [comment]
Sorry I thought this is for openapi-generator.

**Comment by wing328** [comment]
Sorry I thought this is for openapi-generator.

**Comment by SirWayne** [comment]
A release would be cool anyway :)

**Comment by redranch** [comment]
Hi, I would also be keen to see support for javax.validation if possible? We are starting to use openapi-codegen quite heavily now so would be cool if it played nice. Any thoughts on when the next release might be? Thanks

**Comment by jmini** [comment]
I can release the project.
Any opinion about the version number? Should it be `0.2.0`?

**Comment by cbornet** [comment]
I guess so. You can do anything you want in semver 0.x.x

**Comment by jmini** [comment]
[Release `0.2.0`](https://github.com/OpenAPITools/jackson-databind-nullable/releases/tag/jackson-databind-nullable-0.2.0) published to maven central.

On `master` the version is updated to `0.2.1-SNAPSHOT`.

---
Travis configuration could be updated to push the different SNAPSHOT versions to https://oss.sonatype.org/content/repositories/snapshots/

---
Note about how to perform a release manually (no maven plugin, no Travis-CI):
https://github.com/OpenAPITools/jackson-databind-nullable/wiki/Perform-a-release

**Comment by SirWayne** [comment]
@jmini thanks

**Comment by cbornet** [comment]
Now we need to update openapi-generator's templates
